/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationWeddingsSpainRouteImport } from './routes/destination-weddings-spain'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PtIndexRouteImport } from './routes/pt.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PtSobreRouteImport } from './routes/pt.sobre'
import { Route as PtServicosRouteImport } from './routes/pt.servicos'
import { Route as PtParceirosRouteImport } from './routes/pt.parceiros'
import { Route as PtFaqRouteImport } from './routes/pt.faq'
import { Route as PtDepoimentosRouteImport } from './routes/pt.depoimentos'
import { Route as PtContatoRouteImport } from './routes/pt.contato'
import { Route as PtCasarNaEspanhaRouteImport } from './routes/pt.casar-na-espanha'
import { Route as DestinationWeddingsSpainRegionsRouteImport } from './routes/destination-weddings.spain-regions'
import { Route as DestinationWeddingsSevilleRouteImport } from './routes/destination-weddings.seville'
import { Route as DestinationWeddingsMallorcaRouteImport } from './routes/destination-weddings.mallorca'
import { Route as DestinationWeddingsIbizaRouteImport } from './routes/destination-weddings.ibiza'
import { Route as DestinationWeddingsGranadaRouteImport } from './routes/destination-weddings.granada'
import { Route as DestinationWeddingsCostaBravaRouteImport } from './routes/destination-weddings.costa-brava'
import { Route as DestinationWeddingsCataloniaRouteImport } from './routes/destination-weddings.catalonia'
import { Route as BlogWhatIsADestinationWeddingRouteImport } from './routes/blog.what-is-a-destination-wedding'
import { Route as BlogWeddingRegionsInSpainComparedRouteImport } from './routes/blog.wedding-regions-in-spain-compared'
import { Route as BlogWeddingInSpainPlanningTimelineRouteImport } from './routes/blog.wedding-in-spain-planning-timeline'
import { Route as BlogWeddingBudgetTipsSpainRouteImport } from './routes/blog.wedding-budget-tips-spain'
import { Route as BlogCostOfAWeddingInSpainRouteImport } from './routes/blog.cost-of-a-wedding-in-spain'
import { Route as PtBlogIndexRouteImport } from './routes/pt.blog.index'
import { Route as PtCasamentosDestinoSevilhaRouteImport } from './routes/pt.casamentos-destino.sevilha'
import { Route as PtCasamentosDestinoRegioesDaEspanhaRouteImport } from './routes/pt.casamentos-destino.regioes-da-espanha'
import { Route as PtCasamentosDestinoMaiorcaRouteImport } from './routes/pt.casamentos-destino.maiorca'
import { Route as PtCasamentosDestinoIbizaRouteImport } from './routes/pt.casamentos-destino.ibiza'
import { Route as PtCasamentosDestinoGranadaRouteImport } from './routes/pt.casamentos-destino.granada'
import { Route as PtCasamentosDestinoCostaBravaRouteImport } from './routes/pt.casamentos-destino.costa-brava'
import { Route as PtCasamentosDestinoCatalunhaRouteImport } from './routes/pt.casamentos-destino.catalunha'
import { Route as PtBlogRegioesParaCasarNaEspanhaComparadasRouteImport } from './routes/pt.blog.regioes-para-casar-na-espanha-comparadas'
import { Route as PtBlogPlanejamentoCasamentoEspanhaCronogramaRouteImport } from './routes/pt.blog.planejamento-casamento-espanha-cronograma'
import { Route as PtBlogOQueEUmDestinationWeddingRouteImport } from './routes/pt.blog.o-que-e-um-destination-wedding'
import { Route as PtBlogDicasOrcamentoCasamentoEspanhaRouteImport } from './routes/pt.blog.dicas-orcamento-casamento-espanha'
import { Route as PtBlogCustoDeUmCasamentoNaEspanhaRouteImport } from './routes/pt.blog.custo-de-um-casamento-na-espanha'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationWeddingsSpainRoute =
  DestinationWeddingsSpainRouteImport.update({
    id: '/destination-weddings-spain',
    path: '/destination-weddings-spain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtIndexRoute = PtIndexRouteImport.update({
  id: '/pt/',
  path: '/pt/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtSobreRoute = PtSobreRouteImport.update({
  id: '/pt/sobre',
  path: '/pt/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PtServicosRoute = PtServicosRouteImport.update({
  id: '/pt/servicos',
  path: '/pt/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PtParceirosRoute = PtParceirosRouteImport.update({
  id: '/pt/parceiros',
  path: '/pt/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PtFaqRoute = PtFaqRouteImport.update({
  id: '/pt/faq',
  path: '/pt/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PtDepoimentosRoute = PtDepoimentosRouteImport.update({
  id: '/pt/depoimentos',
  path: '/pt/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PtContatoRoute = PtContatoRouteImport.update({
  id: '/pt/contato',
  path: '/pt/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PtCasarNaEspanhaRoute = PtCasarNaEspanhaRouteImport.update({
  id: '/pt/casar-na-espanha',
  path: '/pt/casar-na-espanha',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationWeddingsSpainRegionsRoute =
  DestinationWeddingsSpainRegionsRouteImport.update({
    id: '/destination-weddings/spain-regions',
    path: '/destination-weddings/spain-regions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsSevilleRoute =
  DestinationWeddingsSevilleRouteImport.update({
    id: '/destination-weddings/seville',
    path: '/destination-weddings/seville',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsMallorcaRoute =
  DestinationWeddingsMallorcaRouteImport.update({
    id: '/destination-weddings/mallorca',
    path: '/destination-weddings/mallorca',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsIbizaRoute =
  DestinationWeddingsIbizaRouteImport.update({
    id: '/destination-weddings/ibiza',
    path: '/destination-weddings/ibiza',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsGranadaRoute =
  DestinationWeddingsGranadaRouteImport.update({
    id: '/destination-weddings/granada',
    path: '/destination-weddings/granada',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsCostaBravaRoute =
  DestinationWeddingsCostaBravaRouteImport.update({
    id: '/destination-weddings/costa-brava',
    path: '/destination-weddings/costa-brava',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationWeddingsCataloniaRoute =
  DestinationWeddingsCataloniaRouteImport.update({
    id: '/destination-weddings/catalonia',
    path: '/destination-weddings/catalonia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhatIsADestinationWeddingRoute =
  BlogWhatIsADestinationWeddingRouteImport.update({
    id: '/blog/what-is-a-destination-wedding',
    path: '/blog/what-is-a-destination-wedding',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWeddingRegionsInSpainComparedRoute =
  BlogWeddingRegionsInSpainComparedRouteImport.update({
    id: '/blog/wedding-regions-in-spain-compared',
    path: '/blog/wedding-regions-in-spain-compared',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWeddingInSpainPlanningTimelineRoute =
  BlogWeddingInSpainPlanningTimelineRouteImport.update({
    id: '/blog/wedding-in-spain-planning-timeline',
    path: '/blog/wedding-in-spain-planning-timeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWeddingBudgetTipsSpainRoute =
  BlogWeddingBudgetTipsSpainRouteImport.update({
    id: '/blog/wedding-budget-tips-spain',
    path: '/blog/wedding-budget-tips-spain',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCostOfAWeddingInSpainRoute =
  BlogCostOfAWeddingInSpainRouteImport.update({
    id: '/blog/cost-of-a-wedding-in-spain',
    path: '/blog/cost-of-a-wedding-in-spain',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogIndexRoute = PtBlogIndexRouteImport.update({
  id: '/pt/blog/',
  path: '/pt/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtCasamentosDestinoSevilhaRoute =
  PtCasamentosDestinoSevilhaRouteImport.update({
    id: '/pt/casamentos-destino/sevilha',
    path: '/pt/casamentos-destino/sevilha',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoRegioesDaEspanhaRoute =
  PtCasamentosDestinoRegioesDaEspanhaRouteImport.update({
    id: '/pt/casamentos-destino/regioes-da-espanha',
    path: '/pt/casamentos-destino/regioes-da-espanha',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoMaiorcaRoute =
  PtCasamentosDestinoMaiorcaRouteImport.update({
    id: '/pt/casamentos-destino/maiorca',
    path: '/pt/casamentos-destino/maiorca',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoIbizaRoute =
  PtCasamentosDestinoIbizaRouteImport.update({
    id: '/pt/casamentos-destino/ibiza',
    path: '/pt/casamentos-destino/ibiza',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoGranadaRoute =
  PtCasamentosDestinoGranadaRouteImport.update({
    id: '/pt/casamentos-destino/granada',
    path: '/pt/casamentos-destino/granada',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoCostaBravaRoute =
  PtCasamentosDestinoCostaBravaRouteImport.update({
    id: '/pt/casamentos-destino/costa-brava',
    path: '/pt/casamentos-destino/costa-brava',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtCasamentosDestinoCatalunhaRoute =
  PtCasamentosDestinoCatalunhaRouteImport.update({
    id: '/pt/casamentos-destino/catalunha',
    path: '/pt/casamentos-destino/catalunha',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogRegioesParaCasarNaEspanhaComparadasRoute =
  PtBlogRegioesParaCasarNaEspanhaComparadasRouteImport.update({
    id: '/pt/blog/regioes-para-casar-na-espanha-comparadas',
    path: '/pt/blog/regioes-para-casar-na-espanha-comparadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute =
  PtBlogPlanejamentoCasamentoEspanhaCronogramaRouteImport.update({
    id: '/pt/blog/planejamento-casamento-espanha-cronograma',
    path: '/pt/blog/planejamento-casamento-espanha-cronograma',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogOQueEUmDestinationWeddingRoute =
  PtBlogOQueEUmDestinationWeddingRouteImport.update({
    id: '/pt/blog/o-que-e-um-destination-wedding',
    path: '/pt/blog/o-que-e-um-destination-wedding',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogDicasOrcamentoCasamentoEspanhaRoute =
  PtBlogDicasOrcamentoCasamentoEspanhaRouteImport.update({
    id: '/pt/blog/dicas-orcamento-casamento-espanha',
    path: '/pt/blog/dicas-orcamento-casamento-espanha',
    getParentRoute: () => rootRouteImport,
  } as any)
const PtBlogCustoDeUmCasamentoNaEspanhaRoute =
  PtBlogCustoDeUmCasamentoNaEspanhaRouteImport.update({
    id: '/pt/blog/custo-de-um-casamento-na-espanha',
    path: '/pt/blog/custo-de-um-casamento-na-espanha',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-weddings-spain': typeof DestinationWeddingsSpainRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/cost-of-a-wedding-in-spain': typeof BlogCostOfAWeddingInSpainRoute
  '/blog/wedding-budget-tips-spain': typeof BlogWeddingBudgetTipsSpainRoute
  '/blog/wedding-in-spain-planning-timeline': typeof BlogWeddingInSpainPlanningTimelineRoute
  '/blog/wedding-regions-in-spain-compared': typeof BlogWeddingRegionsInSpainComparedRoute
  '/blog/what-is-a-destination-wedding': typeof BlogWhatIsADestinationWeddingRoute
  '/destination-weddings/catalonia': typeof DestinationWeddingsCataloniaRoute
  '/destination-weddings/costa-brava': typeof DestinationWeddingsCostaBravaRoute
  '/destination-weddings/granada': typeof DestinationWeddingsGranadaRoute
  '/destination-weddings/ibiza': typeof DestinationWeddingsIbizaRoute
  '/destination-weddings/mallorca': typeof DestinationWeddingsMallorcaRoute
  '/destination-weddings/seville': typeof DestinationWeddingsSevilleRoute
  '/destination-weddings/spain-regions': typeof DestinationWeddingsSpainRegionsRoute
  '/pt/casar-na-espanha': typeof PtCasarNaEspanhaRoute
  '/pt/contato': typeof PtContatoRoute
  '/pt/depoimentos': typeof PtDepoimentosRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/parceiros': typeof PtParceirosRoute
  '/pt/servicos': typeof PtServicosRoute
  '/pt/sobre': typeof PtSobreRoute
  '/blog/': typeof BlogIndexRoute
  '/pt/': typeof PtIndexRoute
  '/pt/blog/custo-de-um-casamento-na-espanha': typeof PtBlogCustoDeUmCasamentoNaEspanhaRoute
  '/pt/blog/dicas-orcamento-casamento-espanha': typeof PtBlogDicasOrcamentoCasamentoEspanhaRoute
  '/pt/blog/o-que-e-um-destination-wedding': typeof PtBlogOQueEUmDestinationWeddingRoute
  '/pt/blog/planejamento-casamento-espanha-cronograma': typeof PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute
  '/pt/blog/regioes-para-casar-na-espanha-comparadas': typeof PtBlogRegioesParaCasarNaEspanhaComparadasRoute
  '/pt/casamentos-destino/catalunha': typeof PtCasamentosDestinoCatalunhaRoute
  '/pt/casamentos-destino/costa-brava': typeof PtCasamentosDestinoCostaBravaRoute
  '/pt/casamentos-destino/granada': typeof PtCasamentosDestinoGranadaRoute
  '/pt/casamentos-destino/ibiza': typeof PtCasamentosDestinoIbizaRoute
  '/pt/casamentos-destino/maiorca': typeof PtCasamentosDestinoMaiorcaRoute
  '/pt/casamentos-destino/regioes-da-espanha': typeof PtCasamentosDestinoRegioesDaEspanhaRoute
  '/pt/casamentos-destino/sevilha': typeof PtCasamentosDestinoSevilhaRoute
  '/pt/blog/': typeof PtBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-weddings-spain': typeof DestinationWeddingsSpainRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/cost-of-a-wedding-in-spain': typeof BlogCostOfAWeddingInSpainRoute
  '/blog/wedding-budget-tips-spain': typeof BlogWeddingBudgetTipsSpainRoute
  '/blog/wedding-in-spain-planning-timeline': typeof BlogWeddingInSpainPlanningTimelineRoute
  '/blog/wedding-regions-in-spain-compared': typeof BlogWeddingRegionsInSpainComparedRoute
  '/blog/what-is-a-destination-wedding': typeof BlogWhatIsADestinationWeddingRoute
  '/destination-weddings/catalonia': typeof DestinationWeddingsCataloniaRoute
  '/destination-weddings/costa-brava': typeof DestinationWeddingsCostaBravaRoute
  '/destination-weddings/granada': typeof DestinationWeddingsGranadaRoute
  '/destination-weddings/ibiza': typeof DestinationWeddingsIbizaRoute
  '/destination-weddings/mallorca': typeof DestinationWeddingsMallorcaRoute
  '/destination-weddings/seville': typeof DestinationWeddingsSevilleRoute
  '/destination-weddings/spain-regions': typeof DestinationWeddingsSpainRegionsRoute
  '/pt/casar-na-espanha': typeof PtCasarNaEspanhaRoute
  '/pt/contato': typeof PtContatoRoute
  '/pt/depoimentos': typeof PtDepoimentosRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/parceiros': typeof PtParceirosRoute
  '/pt/servicos': typeof PtServicosRoute
  '/pt/sobre': typeof PtSobreRoute
  '/blog': typeof BlogIndexRoute
  '/pt': typeof PtIndexRoute
  '/pt/blog/custo-de-um-casamento-na-espanha': typeof PtBlogCustoDeUmCasamentoNaEspanhaRoute
  '/pt/blog/dicas-orcamento-casamento-espanha': typeof PtBlogDicasOrcamentoCasamentoEspanhaRoute
  '/pt/blog/o-que-e-um-destination-wedding': typeof PtBlogOQueEUmDestinationWeddingRoute
  '/pt/blog/planejamento-casamento-espanha-cronograma': typeof PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute
  '/pt/blog/regioes-para-casar-na-espanha-comparadas': typeof PtBlogRegioesParaCasarNaEspanhaComparadasRoute
  '/pt/casamentos-destino/catalunha': typeof PtCasamentosDestinoCatalunhaRoute
  '/pt/casamentos-destino/costa-brava': typeof PtCasamentosDestinoCostaBravaRoute
  '/pt/casamentos-destino/granada': typeof PtCasamentosDestinoGranadaRoute
  '/pt/casamentos-destino/ibiza': typeof PtCasamentosDestinoIbizaRoute
  '/pt/casamentos-destino/maiorca': typeof PtCasamentosDestinoMaiorcaRoute
  '/pt/casamentos-destino/regioes-da-espanha': typeof PtCasamentosDestinoRegioesDaEspanhaRoute
  '/pt/casamentos-destino/sevilha': typeof PtCasamentosDestinoSevilhaRoute
  '/pt/blog': typeof PtBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-weddings-spain': typeof DestinationWeddingsSpainRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/cost-of-a-wedding-in-spain': typeof BlogCostOfAWeddingInSpainRoute
  '/blog/wedding-budget-tips-spain': typeof BlogWeddingBudgetTipsSpainRoute
  '/blog/wedding-in-spain-planning-timeline': typeof BlogWeddingInSpainPlanningTimelineRoute
  '/blog/wedding-regions-in-spain-compared': typeof BlogWeddingRegionsInSpainComparedRoute
  '/blog/what-is-a-destination-wedding': typeof BlogWhatIsADestinationWeddingRoute
  '/destination-weddings/catalonia': typeof DestinationWeddingsCataloniaRoute
  '/destination-weddings/costa-brava': typeof DestinationWeddingsCostaBravaRoute
  '/destination-weddings/granada': typeof DestinationWeddingsGranadaRoute
  '/destination-weddings/ibiza': typeof DestinationWeddingsIbizaRoute
  '/destination-weddings/mallorca': typeof DestinationWeddingsMallorcaRoute
  '/destination-weddings/seville': typeof DestinationWeddingsSevilleRoute
  '/destination-weddings/spain-regions': typeof DestinationWeddingsSpainRegionsRoute
  '/pt/casar-na-espanha': typeof PtCasarNaEspanhaRoute
  '/pt/contato': typeof PtContatoRoute
  '/pt/depoimentos': typeof PtDepoimentosRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/parceiros': typeof PtParceirosRoute
  '/pt/servicos': typeof PtServicosRoute
  '/pt/sobre': typeof PtSobreRoute
  '/blog/': typeof BlogIndexRoute
  '/pt/': typeof PtIndexRoute
  '/pt/blog/custo-de-um-casamento-na-espanha': typeof PtBlogCustoDeUmCasamentoNaEspanhaRoute
  '/pt/blog/dicas-orcamento-casamento-espanha': typeof PtBlogDicasOrcamentoCasamentoEspanhaRoute
  '/pt/blog/o-que-e-um-destination-wedding': typeof PtBlogOQueEUmDestinationWeddingRoute
  '/pt/blog/planejamento-casamento-espanha-cronograma': typeof PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute
  '/pt/blog/regioes-para-casar-na-espanha-comparadas': typeof PtBlogRegioesParaCasarNaEspanhaComparadasRoute
  '/pt/casamentos-destino/catalunha': typeof PtCasamentosDestinoCatalunhaRoute
  '/pt/casamentos-destino/costa-brava': typeof PtCasamentosDestinoCostaBravaRoute
  '/pt/casamentos-destino/granada': typeof PtCasamentosDestinoGranadaRoute
  '/pt/casamentos-destino/ibiza': typeof PtCasamentosDestinoIbizaRoute
  '/pt/casamentos-destino/maiorca': typeof PtCasamentosDestinoMaiorcaRoute
  '/pt/casamentos-destino/regioes-da-espanha': typeof PtCasamentosDestinoRegioesDaEspanhaRoute
  '/pt/casamentos-destino/sevilha': typeof PtCasamentosDestinoSevilhaRoute
  '/pt/blog/': typeof PtBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/destination-weddings-spain'
    | '/faq'
    | '/partners'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/cost-of-a-wedding-in-spain'
    | '/blog/wedding-budget-tips-spain'
    | '/blog/wedding-in-spain-planning-timeline'
    | '/blog/wedding-regions-in-spain-compared'
    | '/blog/what-is-a-destination-wedding'
    | '/destination-weddings/catalonia'
    | '/destination-weddings/costa-brava'
    | '/destination-weddings/granada'
    | '/destination-weddings/ibiza'
    | '/destination-weddings/mallorca'
    | '/destination-weddings/seville'
    | '/destination-weddings/spain-regions'
    | '/pt/casar-na-espanha'
    | '/pt/contato'
    | '/pt/depoimentos'
    | '/pt/faq'
    | '/pt/parceiros'
    | '/pt/servicos'
    | '/pt/sobre'
    | '/blog/'
    | '/pt/'
    | '/pt/blog/custo-de-um-casamento-na-espanha'
    | '/pt/blog/dicas-orcamento-casamento-espanha'
    | '/pt/blog/o-que-e-um-destination-wedding'
    | '/pt/blog/planejamento-casamento-espanha-cronograma'
    | '/pt/blog/regioes-para-casar-na-espanha-comparadas'
    | '/pt/casamentos-destino/catalunha'
    | '/pt/casamentos-destino/costa-brava'
    | '/pt/casamentos-destino/granada'
    | '/pt/casamentos-destino/ibiza'
    | '/pt/casamentos-destino/maiorca'
    | '/pt/casamentos-destino/regioes-da-espanha'
    | '/pt/casamentos-destino/sevilha'
    | '/pt/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destination-weddings-spain'
    | '/faq'
    | '/partners'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/cost-of-a-wedding-in-spain'
    | '/blog/wedding-budget-tips-spain'
    | '/blog/wedding-in-spain-planning-timeline'
    | '/blog/wedding-regions-in-spain-compared'
    | '/blog/what-is-a-destination-wedding'
    | '/destination-weddings/catalonia'
    | '/destination-weddings/costa-brava'
    | '/destination-weddings/granada'
    | '/destination-weddings/ibiza'
    | '/destination-weddings/mallorca'
    | '/destination-weddings/seville'
    | '/destination-weddings/spain-regions'
    | '/pt/casar-na-espanha'
    | '/pt/contato'
    | '/pt/depoimentos'
    | '/pt/faq'
    | '/pt/parceiros'
    | '/pt/servicos'
    | '/pt/sobre'
    | '/blog'
    | '/pt'
    | '/pt/blog/custo-de-um-casamento-na-espanha'
    | '/pt/blog/dicas-orcamento-casamento-espanha'
    | '/pt/blog/o-que-e-um-destination-wedding'
    | '/pt/blog/planejamento-casamento-espanha-cronograma'
    | '/pt/blog/regioes-para-casar-na-espanha-comparadas'
    | '/pt/casamentos-destino/catalunha'
    | '/pt/casamentos-destino/costa-brava'
    | '/pt/casamentos-destino/granada'
    | '/pt/casamentos-destino/ibiza'
    | '/pt/casamentos-destino/maiorca'
    | '/pt/casamentos-destino/regioes-da-espanha'
    | '/pt/casamentos-destino/sevilha'
    | '/pt/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/destination-weddings-spain'
    | '/faq'
    | '/partners'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/cost-of-a-wedding-in-spain'
    | '/blog/wedding-budget-tips-spain'
    | '/blog/wedding-in-spain-planning-timeline'
    | '/blog/wedding-regions-in-spain-compared'
    | '/blog/what-is-a-destination-wedding'
    | '/destination-weddings/catalonia'
    | '/destination-weddings/costa-brava'
    | '/destination-weddings/granada'
    | '/destination-weddings/ibiza'
    | '/destination-weddings/mallorca'
    | '/destination-weddings/seville'
    | '/destination-weddings/spain-regions'
    | '/pt/casar-na-espanha'
    | '/pt/contato'
    | '/pt/depoimentos'
    | '/pt/faq'
    | '/pt/parceiros'
    | '/pt/servicos'
    | '/pt/sobre'
    | '/blog/'
    | '/pt/'
    | '/pt/blog/custo-de-um-casamento-na-espanha'
    | '/pt/blog/dicas-orcamento-casamento-espanha'
    | '/pt/blog/o-que-e-um-destination-wedding'
    | '/pt/blog/planejamento-casamento-espanha-cronograma'
    | '/pt/blog/regioes-para-casar-na-espanha-comparadas'
    | '/pt/casamentos-destino/catalunha'
    | '/pt/casamentos-destino/costa-brava'
    | '/pt/casamentos-destino/granada'
    | '/pt/casamentos-destino/ibiza'
    | '/pt/casamentos-destino/maiorca'
    | '/pt/casamentos-destino/regioes-da-espanha'
    | '/pt/casamentos-destino/sevilha'
    | '/pt/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationWeddingsSpainRoute: typeof DestinationWeddingsSpainRoute
  FaqRoute: typeof FaqRoute
  PartnersRoute: typeof PartnersRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogCostOfAWeddingInSpainRoute: typeof BlogCostOfAWeddingInSpainRoute
  BlogWeddingBudgetTipsSpainRoute: typeof BlogWeddingBudgetTipsSpainRoute
  BlogWeddingInSpainPlanningTimelineRoute: typeof BlogWeddingInSpainPlanningTimelineRoute
  BlogWeddingRegionsInSpainComparedRoute: typeof BlogWeddingRegionsInSpainComparedRoute
  BlogWhatIsADestinationWeddingRoute: typeof BlogWhatIsADestinationWeddingRoute
  DestinationWeddingsCataloniaRoute: typeof DestinationWeddingsCataloniaRoute
  DestinationWeddingsCostaBravaRoute: typeof DestinationWeddingsCostaBravaRoute
  DestinationWeddingsGranadaRoute: typeof DestinationWeddingsGranadaRoute
  DestinationWeddingsIbizaRoute: typeof DestinationWeddingsIbizaRoute
  DestinationWeddingsMallorcaRoute: typeof DestinationWeddingsMallorcaRoute
  DestinationWeddingsSevilleRoute: typeof DestinationWeddingsSevilleRoute
  DestinationWeddingsSpainRegionsRoute: typeof DestinationWeddingsSpainRegionsRoute
  PtCasarNaEspanhaRoute: typeof PtCasarNaEspanhaRoute
  PtContatoRoute: typeof PtContatoRoute
  PtDepoimentosRoute: typeof PtDepoimentosRoute
  PtFaqRoute: typeof PtFaqRoute
  PtParceirosRoute: typeof PtParceirosRoute
  PtServicosRoute: typeof PtServicosRoute
  PtSobreRoute: typeof PtSobreRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PtIndexRoute: typeof PtIndexRoute
  PtBlogCustoDeUmCasamentoNaEspanhaRoute: typeof PtBlogCustoDeUmCasamentoNaEspanhaRoute
  PtBlogDicasOrcamentoCasamentoEspanhaRoute: typeof PtBlogDicasOrcamentoCasamentoEspanhaRoute
  PtBlogOQueEUmDestinationWeddingRoute: typeof PtBlogOQueEUmDestinationWeddingRoute
  PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute: typeof PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute
  PtBlogRegioesParaCasarNaEspanhaComparadasRoute: typeof PtBlogRegioesParaCasarNaEspanhaComparadasRoute
  PtCasamentosDestinoCatalunhaRoute: typeof PtCasamentosDestinoCatalunhaRoute
  PtCasamentosDestinoCostaBravaRoute: typeof PtCasamentosDestinoCostaBravaRoute
  PtCasamentosDestinoGranadaRoute: typeof PtCasamentosDestinoGranadaRoute
  PtCasamentosDestinoIbizaRoute: typeof PtCasamentosDestinoIbizaRoute
  PtCasamentosDestinoMaiorcaRoute: typeof PtCasamentosDestinoMaiorcaRoute
  PtCasamentosDestinoRegioesDaEspanhaRoute: typeof PtCasamentosDestinoRegioesDaEspanhaRoute
  PtCasamentosDestinoSevilhaRoute: typeof PtCasamentosDestinoSevilhaRoute
  PtBlogIndexRoute: typeof PtBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings-spain': {
      id: '/destination-weddings-spain'
      path: '/destination-weddings-spain'
      fullPath: '/destination-weddings-spain'
      preLoaderRoute: typeof DestinationWeddingsSpainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/': {
      id: '/pt/'
      path: '/pt'
      fullPath: '/pt/'
      preLoaderRoute: typeof PtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/sobre': {
      id: '/pt/sobre'
      path: '/pt/sobre'
      fullPath: '/pt/sobre'
      preLoaderRoute: typeof PtSobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/servicos': {
      id: '/pt/servicos'
      path: '/pt/servicos'
      fullPath: '/pt/servicos'
      preLoaderRoute: typeof PtServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/parceiros': {
      id: '/pt/parceiros'
      path: '/pt/parceiros'
      fullPath: '/pt/parceiros'
      preLoaderRoute: typeof PtParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/faq': {
      id: '/pt/faq'
      path: '/pt/faq'
      fullPath: '/pt/faq'
      preLoaderRoute: typeof PtFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/depoimentos': {
      id: '/pt/depoimentos'
      path: '/pt/depoimentos'
      fullPath: '/pt/depoimentos'
      preLoaderRoute: typeof PtDepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/contato': {
      id: '/pt/contato'
      path: '/pt/contato'
      fullPath: '/pt/contato'
      preLoaderRoute: typeof PtContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casar-na-espanha': {
      id: '/pt/casar-na-espanha'
      path: '/pt/casar-na-espanha'
      fullPath: '/pt/casar-na-espanha'
      preLoaderRoute: typeof PtCasarNaEspanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/spain-regions': {
      id: '/destination-weddings/spain-regions'
      path: '/destination-weddings/spain-regions'
      fullPath: '/destination-weddings/spain-regions'
      preLoaderRoute: typeof DestinationWeddingsSpainRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/seville': {
      id: '/destination-weddings/seville'
      path: '/destination-weddings/seville'
      fullPath: '/destination-weddings/seville'
      preLoaderRoute: typeof DestinationWeddingsSevilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/mallorca': {
      id: '/destination-weddings/mallorca'
      path: '/destination-weddings/mallorca'
      fullPath: '/destination-weddings/mallorca'
      preLoaderRoute: typeof DestinationWeddingsMallorcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/ibiza': {
      id: '/destination-weddings/ibiza'
      path: '/destination-weddings/ibiza'
      fullPath: '/destination-weddings/ibiza'
      preLoaderRoute: typeof DestinationWeddingsIbizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/granada': {
      id: '/destination-weddings/granada'
      path: '/destination-weddings/granada'
      fullPath: '/destination-weddings/granada'
      preLoaderRoute: typeof DestinationWeddingsGranadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/costa-brava': {
      id: '/destination-weddings/costa-brava'
      path: '/destination-weddings/costa-brava'
      fullPath: '/destination-weddings/costa-brava'
      preLoaderRoute: typeof DestinationWeddingsCostaBravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings/catalonia': {
      id: '/destination-weddings/catalonia'
      path: '/destination-weddings/catalonia'
      fullPath: '/destination-weddings/catalonia'
      preLoaderRoute: typeof DestinationWeddingsCataloniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-a-destination-wedding': {
      id: '/blog/what-is-a-destination-wedding'
      path: '/blog/what-is-a-destination-wedding'
      fullPath: '/blog/what-is-a-destination-wedding'
      preLoaderRoute: typeof BlogWhatIsADestinationWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wedding-regions-in-spain-compared': {
      id: '/blog/wedding-regions-in-spain-compared'
      path: '/blog/wedding-regions-in-spain-compared'
      fullPath: '/blog/wedding-regions-in-spain-compared'
      preLoaderRoute: typeof BlogWeddingRegionsInSpainComparedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wedding-in-spain-planning-timeline': {
      id: '/blog/wedding-in-spain-planning-timeline'
      path: '/blog/wedding-in-spain-planning-timeline'
      fullPath: '/blog/wedding-in-spain-planning-timeline'
      preLoaderRoute: typeof BlogWeddingInSpainPlanningTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wedding-budget-tips-spain': {
      id: '/blog/wedding-budget-tips-spain'
      path: '/blog/wedding-budget-tips-spain'
      fullPath: '/blog/wedding-budget-tips-spain'
      preLoaderRoute: typeof BlogWeddingBudgetTipsSpainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cost-of-a-wedding-in-spain': {
      id: '/blog/cost-of-a-wedding-in-spain'
      path: '/blog/cost-of-a-wedding-in-spain'
      fullPath: '/blog/cost-of-a-wedding-in-spain'
      preLoaderRoute: typeof BlogCostOfAWeddingInSpainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/': {
      id: '/pt/blog/'
      path: '/pt/blog'
      fullPath: '/pt/blog/'
      preLoaderRoute: typeof PtBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/sevilha': {
      id: '/pt/casamentos-destino/sevilha'
      path: '/pt/casamentos-destino/sevilha'
      fullPath: '/pt/casamentos-destino/sevilha'
      preLoaderRoute: typeof PtCasamentosDestinoSevilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/regioes-da-espanha': {
      id: '/pt/casamentos-destino/regioes-da-espanha'
      path: '/pt/casamentos-destino/regioes-da-espanha'
      fullPath: '/pt/casamentos-destino/regioes-da-espanha'
      preLoaderRoute: typeof PtCasamentosDestinoRegioesDaEspanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/maiorca': {
      id: '/pt/casamentos-destino/maiorca'
      path: '/pt/casamentos-destino/maiorca'
      fullPath: '/pt/casamentos-destino/maiorca'
      preLoaderRoute: typeof PtCasamentosDestinoMaiorcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/ibiza': {
      id: '/pt/casamentos-destino/ibiza'
      path: '/pt/casamentos-destino/ibiza'
      fullPath: '/pt/casamentos-destino/ibiza'
      preLoaderRoute: typeof PtCasamentosDestinoIbizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/granada': {
      id: '/pt/casamentos-destino/granada'
      path: '/pt/casamentos-destino/granada'
      fullPath: '/pt/casamentos-destino/granada'
      preLoaderRoute: typeof PtCasamentosDestinoGranadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/costa-brava': {
      id: '/pt/casamentos-destino/costa-brava'
      path: '/pt/casamentos-destino/costa-brava'
      fullPath: '/pt/casamentos-destino/costa-brava'
      preLoaderRoute: typeof PtCasamentosDestinoCostaBravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/casamentos-destino/catalunha': {
      id: '/pt/casamentos-destino/catalunha'
      path: '/pt/casamentos-destino/catalunha'
      fullPath: '/pt/casamentos-destino/catalunha'
      preLoaderRoute: typeof PtCasamentosDestinoCatalunhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/regioes-para-casar-na-espanha-comparadas': {
      id: '/pt/blog/regioes-para-casar-na-espanha-comparadas'
      path: '/pt/blog/regioes-para-casar-na-espanha-comparadas'
      fullPath: '/pt/blog/regioes-para-casar-na-espanha-comparadas'
      preLoaderRoute: typeof PtBlogRegioesParaCasarNaEspanhaComparadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/planejamento-casamento-espanha-cronograma': {
      id: '/pt/blog/planejamento-casamento-espanha-cronograma'
      path: '/pt/blog/planejamento-casamento-espanha-cronograma'
      fullPath: '/pt/blog/planejamento-casamento-espanha-cronograma'
      preLoaderRoute: typeof PtBlogPlanejamentoCasamentoEspanhaCronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/o-que-e-um-destination-wedding': {
      id: '/pt/blog/o-que-e-um-destination-wedding'
      path: '/pt/blog/o-que-e-um-destination-wedding'
      fullPath: '/pt/blog/o-que-e-um-destination-wedding'
      preLoaderRoute: typeof PtBlogOQueEUmDestinationWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/dicas-orcamento-casamento-espanha': {
      id: '/pt/blog/dicas-orcamento-casamento-espanha'
      path: '/pt/blog/dicas-orcamento-casamento-espanha'
      fullPath: '/pt/blog/dicas-orcamento-casamento-espanha'
      preLoaderRoute: typeof PtBlogDicasOrcamentoCasamentoEspanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/blog/custo-de-um-casamento-na-espanha': {
      id: '/pt/blog/custo-de-um-casamento-na-espanha'
      path: '/pt/blog/custo-de-um-casamento-na-espanha'
      fullPath: '/pt/blog/custo-de-um-casamento-na-espanha'
      preLoaderRoute: typeof PtBlogCustoDeUmCasamentoNaEspanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationWeddingsSpainRoute: DestinationWeddingsSpainRoute,
  FaqRoute: FaqRoute,
  PartnersRoute: PartnersRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogCostOfAWeddingInSpainRoute: BlogCostOfAWeddingInSpainRoute,
  BlogWeddingBudgetTipsSpainRoute: BlogWeddingBudgetTipsSpainRoute,
  BlogWeddingInSpainPlanningTimelineRoute:
    BlogWeddingInSpainPlanningTimelineRoute,
  BlogWeddingRegionsInSpainComparedRoute:
    BlogWeddingRegionsInSpainComparedRoute,
  BlogWhatIsADestinationWeddingRoute: BlogWhatIsADestinationWeddingRoute,
  DestinationWeddingsCataloniaRoute: DestinationWeddingsCataloniaRoute,
  DestinationWeddingsCostaBravaRoute: DestinationWeddingsCostaBravaRoute,
  DestinationWeddingsGranadaRoute: DestinationWeddingsGranadaRoute,
  DestinationWeddingsIbizaRoute: DestinationWeddingsIbizaRoute,
  DestinationWeddingsMallorcaRoute: DestinationWeddingsMallorcaRoute,
  DestinationWeddingsSevilleRoute: DestinationWeddingsSevilleRoute,
  DestinationWeddingsSpainRegionsRoute: DestinationWeddingsSpainRegionsRoute,
  PtCasarNaEspanhaRoute: PtCasarNaEspanhaRoute,
  PtContatoRoute: PtContatoRoute,
  PtDepoimentosRoute: PtDepoimentosRoute,
  PtFaqRoute: PtFaqRoute,
  PtParceirosRoute: PtParceirosRoute,
  PtServicosRoute: PtServicosRoute,
  PtSobreRoute: PtSobreRoute,
  BlogIndexRoute: BlogIndexRoute,
  PtIndexRoute: PtIndexRoute,
  PtBlogCustoDeUmCasamentoNaEspanhaRoute:
    PtBlogCustoDeUmCasamentoNaEspanhaRoute,
  PtBlogDicasOrcamentoCasamentoEspanhaRoute:
    PtBlogDicasOrcamentoCasamentoEspanhaRoute,
  PtBlogOQueEUmDestinationWeddingRoute: PtBlogOQueEUmDestinationWeddingRoute,
  PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute:
    PtBlogPlanejamentoCasamentoEspanhaCronogramaRoute,
  PtBlogRegioesParaCasarNaEspanhaComparadasRoute:
    PtBlogRegioesParaCasarNaEspanhaComparadasRoute,
  PtCasamentosDestinoCatalunhaRoute: PtCasamentosDestinoCatalunhaRoute,
  PtCasamentosDestinoCostaBravaRoute: PtCasamentosDestinoCostaBravaRoute,
  PtCasamentosDestinoGranadaRoute: PtCasamentosDestinoGranadaRoute,
  PtCasamentosDestinoIbizaRoute: PtCasamentosDestinoIbizaRoute,
  PtCasamentosDestinoMaiorcaRoute: PtCasamentosDestinoMaiorcaRoute,
  PtCasamentosDestinoRegioesDaEspanhaRoute:
    PtCasamentosDestinoRegioesDaEspanhaRoute,
  PtCasamentosDestinoSevilhaRoute: PtCasamentosDestinoSevilhaRoute,
  PtBlogIndexRoute: PtBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
